### ISSUE TITLE
Add Methods to impute missing data points.

### ISSUE THREAD

**Issue by buabaj** [Team-fastML/fastML#13]
**Is your feature request related to a problem? Please describe.**
we have to work on adding methods to handle missing data. the function will only work with clean, processed data. we can do this by dropping rows that missing data. any other suggestion is welcome.

**Comment by willakuffo** [comment]
I guess we could also replace the missing data point with the mode, median or even the mean in order to maintain sample size

**Comment by buabaj** [comment]
sounds better than dropping the whole row

**Comment by buabaj** [comment]
after a discussion we ended up agreeing to assume users use clean data or we drop rows with missing values which I have successfully implemented.
