### ISSUE TITLE
Add more classification algorithms

### ISSUE THREAD

**Issue by buabaj** [Team-fastML/fastML#6]
**Is your feature request related to a problem? Please describe.**
additional classification algorithms can be added to fastML

**Comment by SageAnanse** [comment]
Yeah, I do not think there is a problem but the addition of another classification algorithm like logistic regression will prove to be beneficial.

**Comment by buabaj** [comment]
do some magic

**Comment by buabaj** [comment]
With what we've been able to build right now, it works with SVC, RandomForest, DecisionTreeClassifier, K-Nearest Neighbors, Logistic Regression and a Neural Net Classifier.I thinks thats enough but everyone is welcome to try others and give feedback. since this is no longer an issue, I'm closing it until further notice.
